### PR TITLE
add support for new platforms - mt6595

### PR DESCRIPTION
**Pull request by carliv**
Hi Bruno,
I updated your tools to support new MTK platforms, which require to pass extra arguments (offsets) in repacking command line. For this the script will create a new file "boot.img-Args.txt" - as example for boot image - will copy in it values like this: "--base 0x10000000 --pagesize 2048 --kernel_offset 0x00008000 --ramdisk_offset 0x01000000 --second_offset 0x00f00000 --tags_offset 0x00000100". They will be shown on the screen also. At repacking all these are passed in command and the resulting image will work in these new phones. It has no impact on older platforms - I tested this myself, and for new platform was tested in zopo zp999 thread. Additionally I created a new script which will only show image infos, if there is no need to unpack it. I compiled again all binaries modules to support these extra arguments, and also I compiled the required modules for info script. I couldn't do it for OSX, but I have the repo with boot-info in my gihub if you can build it. Also mkbootimg has to be compiled again for OSX to accept extra arguments.
Liviu

### CODE REVIEW

**Comment by carliv** [comment]
I have an ideea for repacking script https://github.com/carliv/mtk-tools/commit/80e82ffbf4a1f73947685fadee261bda5afb10a6
This will show on screen the elements of repacking command and I think will be good for review or only to see what's going on. What do you think?

**Comment by bgcngm** [comment]
First of all, happy new year! I was also going to change repack script to show more info. I can merge, but I'll rework that.

**Comment by carliv** [comment]
Happy new year for you too! Sorry I forgot, I wake up and started to work and I forgot about that :)
Ah, I wanted to share the ideea with you, don't have to merge that if you want to offer a better solution. I just was thinking it will be good to see what the repacking command actually do.

**Comment by bgcngm** [comment]
Yeah, it's a good idea, to show more info when repacking. Thanks!

**Comment by bgcngm** [comment]
Here's what I had been thinking: 7f6453df7f2b20c457f8673c81598610d0c82c06

**Comment by carliv** [comment]
I see... I don't know what to say, I was thinking on something different, because now if the repack will be immediately will be two bloks with info on screen, very much alike. My ideea was closer to this: http://i.imgur.com/FNTXP9n.png
But if you are the one who decide what's best.

**Comment by bgcngm** [comment]
Yes, the output is very similar, but I find it convenient. I also added your suggestion: a9d9b27dd715349e8bc1a076273f67a1aaad1c7c.

**Comment by carliv** [comment]
Looks ok http://i.imgur.com/QEJKhRL.png
but can you include an option to turn off the block info display from repacking when executing verbose?
I think that will be a better way to manage it.. just my 2 cents

**Comment by bgcngm** [comment]
Okay, I'll think about it. But in that case I should change switch name to something else, because "more_verbose" should not mean less. :p

**Comment by carliv** [comment]
:) Yes, I didn't think about that. Then maybe it can be a new mod, alternative to verbose (something with else if), that will display only the command line, and you could call it technical or something, because you can see the command (almost) as it is passed on execution.

**Comment by bgcngm** [comment]
I'll name it "debug" and I plan to add more debug info than just the command line arguments for mkbootimg. As it is a debug mode, I also think to leave repacked ramdisk.cpio file(s) in the working dir. It is a preparation for the eventual support of other ramdisk compression methods. What do you think?

**Comment by carliv** [comment]
Yes, I think it's a good ideea. About a new ramdisk compression method I have some doubts. As I said in your thread It's highly experimental for linux and I never heard of plans to be implemented on Android, but it's a good thing to be ready for a change and to think in advance. :+1:

**Comment by bgcngm** [comment]
Here's the output:

image

**Comment by carliv** [comment]
I really like this :+1: 
One thing though, not maybe important, but still. Can you replace the path from mkbootimg with "./"? It will be like a manual command fallback that the user can just copy and paste to try manual mode.

**Comment by bgcngm** [comment]
I could, but in some cases it could cause confusion to the user. For example, if you see my screenshot, I have mkbootimg binary in a different location other than the working dir.

What could be done is to simply print: "mkbootimg --kernel (...)".

**Comment by carliv** [comment]
Ah, that works too. It will have to type that manually first. Anyway this is just my ideea, if you don't like it don't have to use it. :) 
I thought about that after I saw people got confused with arguments, options, etc, in command line.

**Comment by bgcngm** [comment]
Well... debug mode is for advanced users, after all.

**Comment by bgcngm** [comment]
I want your opinion about what ramdisk.cpio files to leave in the working directory. Just the repacked one which includes MTK special header (but then it would not be possible to open it with a archive manager) or both (the one without the header and the one with the header).

**Comment by carliv** [comment]
I don't know what to say... Both I think it is too much, the one with header it will require a dd operation before extracting... Is it possible to let only the one without header?

**Comment by bgcngm** [comment]
Sure, and eventually save the header as a separate file.

**Comment by carliv** [comment]
Yes, this the best option.

**Comment by bgcngm** [comment]
Should I also leave out the newly added input file information, while unpacking under debug mode? I think so, to be coherent with the repack script.

**Comment by carliv** [comment]
Well, I thought those are important too, but not to display in a block info, just saved in a separate file... If I understand right, you see the debug mode strictly regarding the unpack script and binary functionalities, but I'm thinking to be more as a "service" tool, when you can see what's happen and to spot any malfunction. This is the reason I wanted the repacking command displayed: if the repacked image doesn't work it can be compared the info from it with those from unpacking, then if the appending header is displayed too somehow, it can be checked if that worked too. To sum up, I was thinking on a process when you can see actions performed one by one and displayed, both for unpacking and repacking, and to see if any error pops up. I don't know if it's possible this way.

**Comment by bgcngm** [comment]
Done: 03f9d210b3a37fe3bd499eaa21a7eb6ee8e97875

Further discussion about eventual support of other ramdisk compression methods, should be done in the support thread.

**Comment by carliv** [comment]
Looks good :+1:   http://i.imgur.com/pvnyJs6.png
But there is a problem, the info-only option doesn't work: I mean the script does unpack the image not just display the info http://i.imgur.com/8ViJS00.png
And also for unpacking, if no option is used, it will print an error on screen just under Valid signature found  http://i.imgur.com/P23IPDZ.png
For repacking with debug everything goes nicely http://i.imgur.com/PV3c46t.png
but if debug option isn't used, things looks different...  http://i.imgur.com/zBl1mEW.png
probably is a misplacement of Base address..

**Comment by bgcngm** [comment]
The problem with the unpack script was my bad. I should have tested info_only option and I did not. Anyway, a fix is already in place and will be pushed in the meanwhile.

As for the strange output you see while repacking has to do with an "old" format of args files. Make sure you delete the file or unpack boot/recovery again to generate the new extra args file according to the new layout.

**Comment by carliv** [comment]
Yes, it's fixed now and everything works fine. Good job!
And you're right about that old args file: I deleted all old unpacked files and tried again with success.

**Comment by carliv** [comment]
Hi again. There is a problem with last repacking script. I couldn't figure out what is (I'm also a bit sick now), but any repacked image doesn't work in any platform (tested 6572, 6589, 6592 and the new 6752): all blackscreen and reboot for recovery, bootloop for boot. It worked well including this commit https://github.com/bgcngm/mtk-tools/commit/81891ea29624ec4964ee5e45c6c0a8f7749cc42a
I updated after that directly to last version, so I can't say which one brought the problem.

**Comment by bgcngm** [comment]
It could be because I changed the ramdisk repack command a little bit. Try to revert to this commit and let me know if it works: a9d9b27dd715349e8bc1a076273f67a1aaad1c7c.

**Comment by dragonpt** [comment]
Sure, but I'm out of town for the time being, will revert to that commit, and test on my devices, next Saturday.

**Comment by carliv** [comment]
Yes, that one works!

**Comment by bgcngm** [comment]
I have just pushed the fix to the ramdisk repack command. ;)

**Comment by carliv** [comment]
Good, now it's working well.
I recompiled the binaries (solved few warnings during compilation, added all info in usage, removed unecessary stuff - keep only limbincrypt and sha files from include, and that slimed down the module preserving all functionality). If you want I can make a pull request to update them in your official branch too.
screenshot from 2015-01-10 09 39 17

**Comment by bgcngm** [comment]
Sure, send the pull request. Thanks for all the testing.

**Pull request closed without merging**
